### ISSUE TITLE
Colored pages broken in double page mode on latest mpv

### ISSUE THREAD

**Issue by McBaws** [Dudemanguy/mpv-manga-reader#28]
Double page mode is broken on the latest mpv builds (pm anything newer than the most recent stable version). The issue occurs with all of my other scripts removed as well.

On older versions of mpv, the reader automatically detects colored spreads and only displays the one image when they appear. In the newer mpv versions, the spread and next page are displayed at once. The strange thing is this only seems to happen with colored pages. Also, some colored pages are randomly displayed in grayscale.

Here's a sample file which has both of these issues occurring (the contents page becomes grayscale when displayed with the nerv page): https://files.catbox.moe/k8uocs.cbz

**Comment by Dudemanguy** [comment]
This works for me on the latest mpv built from git. I suspect an ffmpeg change would be the culprit.

**Comment by Dudemanguy** [comment]
OK, so this particular sample you posted is `image2`. This is blacklisted in mpv's lavf demuxer (because it doesn't work there at all) and is read by the mf demuxer. There's nothing this script can do in this case because that demuxer is not capable of providing the needed properties to this script so it can make the correct decision.

There's no way this file should have ever worked correctly. Not on the recent stable version either.

**Comment by McBaws** [comment]
Well, something must have changed in a recent commit that breaks the desired behaviour.

Are there any resources you can link to about image2? Would there be a way to convert image files so that they're compatible with the script?

Thank you for your quick response!

**Comment by McBaws** [comment]
Thank you for investigating and reverting the commit! Cheers dude
