### ISSUE TITLE
Conversion from gray to rgb24 in double page mode causes artefacts

### ISSUE THREAD

**Issue by McBaws** [Dudemanguy/mpv-manga-reader#30]
There are weird yellow outlines when viewing these images in double page mode. Might be a problem with whatever filters are being used for the format conversion.

Original files: [test.zip](https://github.com/user-attachments/files/16103750/test.zip)
![Tokyo Ghoul - re - c125 (v12) - p064  dig   VIZ Media   DigitalMangaFan  - 00_00_00 000 - 01](https://github.com/Dudemanguy/mpv-manga-reader/assets/32965045/f176a73a-7198-4e68-9b65-0a787972207c)

**Comment by Dudemanguy** [comment]
The problem is that mpv's autoconverter is kicking in here on the black page:

```
[autoconvert] Converting pal8 -> argb
```

The script is converting the gray page to pal8 not argb. This is what is causing the artifact. Not really sure what the best solution is yet for this edge case.

**Comment by Dudemanguy** [comment]
So I experimentally tested all of the possible format conversions mpv may do internally (which is based on ffmpeg apis of course), at it turns out that gray with any format besides another gray format will always pick argb as the best format. So in fact, I can simplify the entire format conversion business and always use argb when we have gray pages.
