### ISSUE TITLE
I have a problem with continuous mode

### ISSUE THREAD

**Issue by HasanAbbadi** [Dudemanguy/mpv-manga-reader#8]
![Screenshot from 2021-03-26 20-34-09](https://user-images.githubusercontent.com/78548167/112671178-eb4c6380-8e72-11eb-9995-4a9ddf8fc2db.png)
Well, the picture explains it all.

**Comment by Dudemanguy** [comment]
Not a bug. It's unfortunately limitation with mpv. mpv is unable to open an image that has a larger size than your GPU's texture size. Image viewers and the like do various things to work around this, but this is not possible with how mpv currently works. It's easy to hit this error with continuous mode since it shows one really big picture. The only thing you can do is lower the `continuous_size`.
